fit_project/fit_app/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', signin, name='signin'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('home/', home, name='home'),
    path('profilepage/', profilepage, name='profilepage'),
    path('editprofile/', editprofile, name='editprofile'),
    path('createPost/', createPost, name='createPost'),
    path('comments/', comments, name='comments'),
    path('addFood/', addFood, name='addFood'),
    path('viewFood/', viewFood, name='viewFood'),
    path('deleteFood/<int:id>/', deleteFood, name='deleteFood'),
    path('editFood/<int:id>/', editFood, name='editFood'),

    path('viewConsumedCalories/', viewConsumedCalories, name='viewConsumedCalories'),
    path('addConsumedCalories/', addConsumedCalories, name='addConsumedCalories'),
    path('addFoodsCalories/<int:id>/', addFoodsCalories, name='addFoodsCalories'),
    path('addRestFoodsCalories/<int:id>/', addRestFoodsCalories, name='addRestFoodsCalories'),
    path('deleteConsumedCalories/<int:id>/', deleteConsumedCalories, name='deleteConsumedCalories'),

    path('postSection/', postSection, name='postSection'),
    path('friendlist/', friendlist, name='friendlist'),
    path('veiwFriendsProfile/<int:id>', veiwFriendsProfile, name='veiwFriendsProfile'),
    path('Follow/<int:id>', Follow, name='Follow'),
    path('unFollow/<int:id>', unFollow, name='unFollow'),
    path('followerlist/', followerlist, name='followerlist'),   
    path('deleteFollower/<str:userid>', deleteFollower, name='deleteFollower'),
    path('viewrestaurantfood/<str:id>', viewrestaurantfood, name='viewrestaurantfood'),
    path('followinglist/', followinglist, name='followinglist'),
    path('friendFollower/<str:id>', friendFollower, name='friendFollower'),
    path('friendFollowing/<str:id>', friendFollowing, name='friendFollowing'),


    path('restaurantListPage/', restaurantListPage, name='restaurantListPage'),
    path('gymPage/', gymPage, name='gymPage'),
    path('exercisePage/', exercisePage, name='exercisePage'),
    path('restOrSleepPage/', restOrSleepPage, name='restOrSleepPage'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fit_project/fit_project/urls.py
from django.contrib import admin
from django.urls import path, include
from fit_app.views import *
from django.conf import settings
from django.conf.urls.static import static
# import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/', include('restaurantapp.urls')),
    path('', include('fit_app.urls')),

    # path('notifications/', include(notifications.urls, namespace='notifications')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fit_project/fit_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class customUser(AbstractUser):
    GENDER = [('male','Male'),('female','Female')]
    GOAL = [('lose_weight','Lose Weight'),('gain_weight','Gain Weight'),('maintain_weight','Maintain Weight')]

    name = models.CharField(max_length=50,null=True,blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic/',null=True,blank=True)
    dob = models.DateField(null=True,blank=True)
    height = models.FloatField(null=True,blank=True)
    weight = models.FloatField(null=True,blank=True)
    gender = models.CharField(max_length=10,choices=GENDER,null=True,blank=True)
    goal = models.CharField(max_length=20,choices=GOAL,null=True,blank=True)
    user_type = models.CharField(max_length=20,null=True,blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.username
    

class userFollow(models.Model):
    user = models.ForeignKey(customUser, on_delete=models.CASCADE, related_name='follower')
    follow = models.ForeignKey(customUser, on_delete=models.CASCADE, related_name='following')

    def __str__(self):
        return self.user.username + ' follows ' + self.follow.username
    
    
# class userDiet(models.Model):
#     user = models.ForeignKey(customUser, on_delete=models.CASCADE)
#     diet = models.TextField()
#     date = models.DateField(auto_now_add=True)

#     def __str__(self):
#         return self.user.username
    
class userPost(models.Model):
    user = models.ForeignKey(customUser, on_delete=models.CASCADE)
    post = models.TextField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username + ' posted on ' + str(self.date)

class postImage(models.Model):
    userpost = models.ForeignKey(userPost, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_pics/')
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.userpost.user.username
    
class commentsModel(models.Model):
    user = models.ForeignKey(customUser, on_delete=models.CASCADE)
    post = models.ForeignKey(userPost, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username


# class userWeight(models.Model):
#     user = models.ForeignKey(customUser,on_delete=models.CASCADE)
#     weight = models.FloatField()
#     date = models.DateField(auto_now_add=True)

#     def __str__(self):
#         return self.user.username

class ConsumedCalories(models.Model):
    user = models.ForeignKey(customUser, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    calorie_consumed = models.FloatField(default=0)
    date = models.DateField(auto_now_add=True, null=True)
    time = models.TimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.item_name


class foodModel(models.Model):
    user = models.ForeignKey(customUser,on_delete=models.CASCADE)
    food_name = models.CharField(max_length=50)
    calories = models.FloatField(null=True)
    image = models.ImageField(upload_to='food_pics/')

    def __str__(self):
        return self.food_name


class addRestaurantFood(models.Model):
    user = models.ForeignKey(customUser, on_delete=models.CASCADE, null=True)
    food_name = models.CharField(max_length=100)
    calories = models.CharField(max_length=100)
    CATEGORY = [
        ('fruit', 'Fruit'),
        ('vegetable', 'Vegetable'),
        ('grain', 'Grain'),
        ('protein', 'Protein'),
        ('dairy', 'Dairy'),
        ('dessert', 'Dessert'),
        ('beverage', 'Beverage'),
        ('fast_food', 'Fast Food'),
    ]
    category = models.CharField(choices=CATEGORY, max_length=100)
    description = models.TextField()
    price = models.PositiveIntegerField()
    quantity = models.CharField(max_length=100)
    image = models.ImageField(upload_to='restaurantFoods')

    def __str__(self):
        return self.food_name

fit_project/fit_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from .models import *
from datetime import date, timedelta, datetime
# from django.core.serializers import serialize
from django.db.models import Q
from django.urls import reverse
import json
from django.db.models import Sum
# from django.http import HttpRequest, HttpResponse

# Create your views here.

def signin(r):
    if r.method=='POST':
        username = r.POST['username']
        password = r.POST['password']
        user = authenticate(username=username,password=password)
        if user:
            login(r,user)
            return redirect('home')

    return render(r,'register/signin.html')

def signup(r):
    if r.method=='POST':
        name = r.POST['name']
        username = r.POST['username']
        password = r.POST['password']
        gender = r.POST['gender']
        dob = r.POST['dob']
        height = r.POST['height']
        weight = r.POST['weight']
        goal = r.POST['goal']
        profile_pic = r.FILES['profile_pic']
        location = r.POST['location']
        phone = r.POST['phone']
        about = r.POST['about']
        email = r.POST['email']

        user = customUser.objects.create_user(
            username=username,
            password=password,
            name=name,
            gender=gender,
            dob=dob,
            height=height,
            weight=weight,
            goal=goal,
            user_type='user',
            profile_pic=profile_pic,
            location=location,
            phone=phone,
            about=about,
            email=email,
        )
        user.save()
        
        if user:
            login(r,user)
            return redirect('home')

    return render(r,'register/signup.html')

def signout(r):
    logout(r)
    return redirect('signin')

def get_weekly_calories(user):
    start_date = date.today() - timedelta(days=7)
    daily_calories = []
    for i in range(8): 
        day = start_date + timedelta(days=i)
        calories = ConsumedCalories.objects.filter(user=user, date=day).aggregate(total_calories=Sum('calorie_consumed'))['total_calories']
        if calories is None:
            calories = 0
        daily_calories.append((day.strftime('%Y-%m-%d'), calories))
    return daily_calories

def get_weekly_bmr(user):
    bmr = userBMR(user)
    start_date = date.today() - timedelta(days=7)
    weekly_bmr = [[(start_date + timedelta(days=i)).strftime('%Y-%m-%d'), bmr] for i in range(8)]
    return weekly_bmr

@login_required
def home(r):
    user = r.user
    weekly_calories = json.dumps(get_weekly_calories(user))
    weekly_bmr = json.dumps(get_weekly_bmr(user))
    bmr = userBMR(user)
    calSum = today_calories(r)
    user = customUser.objects.get(id=r.user.id)
    total_followers = userFollow.objects.filter(follow=user).count()
    return render(r, 'common/home.html', {'weekly_calories': weekly_calories, 'weekly_bmr': weekly_bmr, 'bmr': bmr, 'calSum': calSum, 'total_followers': total_followers})


@login_required
def profilepage(r):
    user = customUser.objects.get(id=r.user.id)
    total_followers = userFollow.objects.filter(follow=user).count()
    total_following = userFollow.objects.filter(user=user).count()

    postdata = userPost.objects.filter(user=user).order_by('-date','-time')
    postLength = postdata.count()
    
    context = {
        'user': user,
        'total_followers': total_followers,
        'total_following': total_following,
        'postdata': postdata,
        'postLength': postLength,
    }
     
    return render(r,'profile/profilepage.html', context)


@login_required
def createPost(r, next=None):
    if r.method=='POST':
        post = r.POST.get('post')  
        post = userPost(user=r.user,post=post)
        post.save()

        for image in r.FILES.getlist('images'):
            postImage(userpost=post,image=image).save()
        if next:
            return redirect(next)

    return redirect(r.META.get('HTTP_REFERER', '/'))
        
    
def comments(r, next=None):
    if r.method == 'POST':
        comment = r.POST.get('comment')
        comment_id = r.POST.get('id') 
        try:
            post = userPost.objects.get(id=comment_id)
        except userPost.DoesNotExist:
            if next:
                return redirect(next)
        comment_data = commentsModel(user=r.user, post=post, comment=comment)
        comment_data.save()

        if next:
            return redirect(next)

    return redirect(r.META.get('HTTP_REFERER', '/'))

@login_required
def postSection(r):
    postdata = userPost.objects.all().order_by('-date', '-time')
    postLength = postdata.count()

    context = {
        'postdata': postdata,
        'postLength': postLength,
    }

    return render(r, 'profile/postSection.html', context)

def unFollow(r, id, next=None):
    follow = userFollow.objects.filter(user=r.user, follow=customUser.objects.get(id=id))
    follow.delete()
    if next:
        return redirect(next)
    else:
        return redirect(r.META.get('HTTP_REFERER', '/'))


@login_required
def editprofile(r):
    user = customUser.objects.get(id=r.user.id)
    if r.method=='POST':
        user.name = r.POST['name']
        user.username = r.POST['username']
        user.dob = r.POST['dob']
        user.height = r.POST['height']
        user.weight = r.POST['weight']
        user.goal = r.POST['goal']
        user.location = r.POST['location']
        user.about = r.POST['about']
        user.phone = r.POST['phone']

        profile_pic = r.FILES.get('profile_pic')
        if profile_pic:
            user.profile_pic = profile_pic
        else:
            profile_pic1 = r.POST.get('profile_pic1')
            if profile_pic1:
                user.profile_pic = profile_pic1

        user.save()
        return redirect('profilepage')

    return render(r,'profile/editprofile.html')

@login_required
def addFood(r):
    if r.method=='POST':
        food_name = r.POST['food_name']
        calories = r.POST['calories']
        image = r.FILES['image']

        food = foodModel(user=r.user,food_name=food_name,calories=calories,image=image)
        food.save()
        return redirect('viewFood')

    return render(r,'foods_by_user/addFood.html')



@login_required
def viewFood(r):
    if 'search1' in r.GET:
        search = r.GET.get('search1')
        if search:
            foods = foodModel.objects.filter(Q(food_name__icontains=search))
            return render(r,'foods_by_user/viewFood.html',{'foods':foods})
        
    foods = foodModel.objects.filter(user=r.user)
    print(r.path)
    return render(r,'foods_by_user/viewFood.html',{'foods':foods})

@login_required
def editFood(r,id):
    food = foodModel.objects.get(id=id)
    if r.method=='POST':
        food.food_name = r.POST['food_name']
        food.calories = r.POST['calories']

        image = r.FILES.get('image')
        if image:
            food.image = image
        else:
            image1 = r.POST.get('image1')
            if image1:
                food.image = image1

        food.save()
        return redirect('viewFood')

    return render(r,'foods_by_user/editFood.html',{'food':food})

@login_required
def deleteFood(r,id):
    food = foodModel.objects.get(id=id)
    food.delete()
    return redirect('viewFood')

def userAge(user):
    if user.user_type ==  'user':
        today = date.today()
        birthdate = user.dob 
        years = today.year - birthdate.year 
        if today.month < birthdate.month or (today.month == birthdate.month and today.day < birthdate.day):
            years -= 1
        
        next_birthday_month = birthdate.month
        next_birthday_year = today.year if today.month > birthdate.month or (today.month == birthdate.month and today.day >= birthdate.day) else today.year - 1
        next_birthday = date(next_birthday_year, next_birthday_month, birthdate.day)
        
        days_since_last_birthday = (today - next_birthday).days
        days_in_year = 366 if next_birthday_year % 4 == 0 else 365
        
        fractional_year = days_since_last_birthday / days_in_year
        total_age = years + fractional_year
        return f"{total_age:.2f}"

def userBMR(user):
    if user.user_type ==  'user':
        age = float(userAge(user))
        # print('age',age)
        if user.gender == 'male':
            bmr = 66.47 + (13.75 * user.weight) + (5.003 * user.height) - (6.755 * age)
        else:
            bmr = 655.1 + (9.563 * user.weight) + (1.850 * user.height) - (4.676 * age)
        return f"{bmr:.2f}"

def today_consumed(r):
    consumed = ConsumedCalories.objects.filter(user=r.user, date=date.today())
    return consumed

def today_calories(r):
    consumed = ConsumedCalories.objects.filter(user=r.user, date=date.today())
    calSum = sum(c.calorie_consumed for c in consumed)
    return calSum

@login_required
def addConsumedCalories(r):
    if r.method=='POST':
        item_name = r.POST['item_name']
        calorie_consumed = float(r.POST['calorie_consumed'])

        consumed = ConsumedCalories(user=r.user,item_name=item_name,calorie_consumed=calorie_consumed)
        consumed.save()
        return redirect('viewConsumedCalories')
    return render(r,'calories/addConsumedCalories.html')


@login_required
def addFoodsCalories(r, id):
    food = foodModel.objects.get(id=id)
    consumed = ConsumedCalories(user=r.user,item_name=food.food_name,calorie_consumed=food.calories)
    consumed.save()
    return redirect('viewConsumedCalories')

@login_required
def addRestFoodsCalories(r, id):
    food = addRestaurantFood.objects.get(id=id)
    consumed = ConsumedCalories(user=r.user,item_name=food.food_name,calorie_consumed=food.calories)
    consumed.save()
    return redirect('viewConsumedCalories')


@login_required
def deleteConsumedCalories(r, id):
    consumed = ConsumedCalories.objects.get(id=id)
    consumed.delete()

fit_project/fit_app/templates/profile/editprofile.html
{% extends "common/base.html" %}
{% block content %}

<div class="container-fluid">
    <div class="col-xl-6">
        <div class="form-input-content">
            <div class="card login-form mb-0">
                <div class="card-body">
                   
                   <h3 class="text-center">Update Profile</h3>
                   <form class="mt-5 mb-5 login-input" method='post' enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="mr-sm-2">Name</label>
                            <input type="text" class="form-control" name='name' value="{{user.name}}"  placeholder="Enter your name" required>
                        </div>
                        <div class="form-group">
                           <label class="mr-sm-2">Username</label>
                           <input type="text" readonly class="form-control" name='username' value="{{user.username}}"  placeholder="Enter your username" required>
                        </div>
                        <div class="form-group">
                           <label class="mr-sm-2">Email</label>
                           <input type="email" class="form-control" name='email' value="{{user.email}}"  placeholder="Enter your email" required>
                        </div>
                        <div class="form-group">
                           <label class="mr-sm-2">Phone Number</label>
                           <input type="tel" class="form-control" name='phone' value="{{user.phone}}"  placeholder="Enter your phone number" required>
                        </div>
                      
                      <div class="form-group">
                         <label class="mr-sm-2">Gender</label>
                         <select class="custom-select mr-sm-2" name='gender'  value="{{user.gender}}" id="inlineFormCustomSelect">
                            <option selected="selected">Select your gender</option>
                            <option {% if user.gender == 'male' %} selected {% endif %} value="male">Male</option>
                            <option {% if user.gender == 'female' %} selected {% endif %} value="female">Female</option>
                         </select>
                      </div>
                      <div class="form-group">
                         <label class="mr-sm-2">Date of Birth</label>
                         <input type="date" class="form-control" name='dob'  value="{{ user.dob|date:'Y-m-d' }}" required>
                      </div>
                      <div class="form-group">
                         <label class="mr-sm-2">Height</label>
                         <input type="number" class="form-control" name='height' value="{{user.height}}" placeholder="Enter your height in cm" required>
                      </div>
                      <div class="form-group">
                         <label class="mr-sm-2">Weight</label>
                         <input type="number" class="form-control" name='weight' value="{{user.weight}}" placeholder="Enter your weight in kg" required>
                      </div>
                      
                      <div class="form-group">
                         <label class="mr-sm-2">Profile Picture</label>
                         <input type="file" name='profile_pic' class="form-control-file">
                         <input type="hidden" name='profile_pic1'  value="{{user.profile_pic.url}}" class="form-control-file">
                      </div>
                      
                      <div class="form-group">
                         <label class="mr-sm-2">Goal</label>
                         <select class="custom-select mr-sm-2" name='goal' value="{{user.goal}}" id="inlineFormCustomSelect">
                            <option selected="selected">Select a goal</option>
                            <option {% if user.goal == 'lose_weight' %} selected {% endif %} value="lose_weight">Lose Weight</option>
                            <option {% if user.goal == 'gain_weight' %} selected {% endif %} value="gain_weight">Gain Weight</option>
                            <option {% if user.goal == 'maintain_weight' %} selected {% endif %} value="maintain_weight">Maintain Weight</option>
                         </select>
                      </div>
                      
                      <div class="form-group">
                         <label class="mr-sm-2">Location</label>
                         <input type="text" class="form-control" name='location' value="{{user.location}}" placeholder="Enter your location" required>
                      </div>
                      <div class="form-group">
                         <label class="mr-sm-2">About</label>
                         <textarea name="about" id="" class="form-control border">{{user.about}}"</textarea>
                      </div>
                      <button class="btn login-form__btn submit w-100">Update</button>
                   </form>
                   
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

fit_project/fit_app/templates/profile/postSection.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<style>
    ul#imageNames:empty {
    display: none;
}
</style>
<div class="container-fluid">
    <div class="row">

        <div class="col-lg-8 col-xl-9">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'createPost' %}" method='post' class="form-profile" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea class="form-control" name="post" id="textarea" cols="30" rows="2"
                                placeholder="Post a new message"></textarea>
                        </div>
                        <div class="d-flex align-items-center">
                            <ul class="mb-0 form-profile__icons pt-4">
                                <p class="btn btn-transparent p-0 mr-3"><i class="fa fa-user"></i></p>

                                <label for='fileInput' class="mr-3"><p class="btn btn-transparent p-0 mr-3"><i class="fa fa-camera"></i></p></label>
                                <input type="file" id="fileInput" name="images" style="display: none;" multiple accept="image/*">

                            </ul>
                            
                            <button class="btn btn-primary px-3 ml-4">Send</button>
                        </div>
                        <ul id="imageNames"></ul>
                    </form>
                </div>
            </div>
            
            {% if postLength %}
            <div class="card">
                <div class="card-body">
                    
                    {% for post in postdata %}
                        <div class="media media-reply">
                        <img class="mr-3 circle-rounded" src="{{ post.user.profile_pic.url }}" width="50" height="50"  alt="Generic placeholder image">
                        <div class="media-body">
                            <div class="d-sm-flex justify-content-between mb-2">
                                <h5 class="mb-sm-0">{{ post.user.name }}  <small class="text-muted ml-3"> {{post.time}} {{ post.date }} </small>
                                </h5>
                                <div class="media-reply__link">
                                    <button class="btn btn-transparent p-0 mr-3"><i class="fa fa-thumbs-up"></i></button>
                                    <button class="btn btn-transparent p-0 mr-3"><i class="fa fa-thumbs-down"></i></button>
                                    <button type="button" class="btn btn-transparent text-dark font-weight-bold p-0 ml-2" data-toggle="modal" data-id="{{ post.id }}" data-target="#exampleModalCenter"> Reply </button>
                                </div>
                            </div>
                            <p>{{ post.post }}</p>
                            <ul>
                                {% for image in post.postimage_set.all %}
                                        <img src="{{ image.image.url }}" alt="" style="max-height: 10rem; margin-bottom: 8px; border-radius: 8px; border: 1px solid #ccc;">
                                {% endfor %}                               
                            </ul>
                           
                            
                            {% for comment in post.commentsmodel_set.all %}
                            <div class="media mt-3">
                                <img class="mr-3 circle-rounded circle-rounded" src="{{ comment.user.profile_pic.url }}" width="50"
                                    height="50" alt="Generic placeholder image">
                                <div class="media-body">
                                    <div class="d-sm-flex justify-content-between mb-2">
                                        <h5 class="mb-sm-0">{{ comment.user.name }} <small class="text-muted ml-3"> on {{ comment.date }} {{ comment.time }}</small></h5>
                                        
                                    </div>
                                    <p>{{comment.comment}}</p>
                                </div>
                            </div>
                            {% endfor %}

                            <div class="border">
                                <div class="card-body">
                                    <form action="{% url 'comments' %}" method='post' class="form-profile" >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type='hidden' name="id" id='id' value="{{post.id}}">
                                            <textarea class="form-control" name="comment" id="textarea" cols="30" rows="2" placeholder="Post a new message"></textarea>
                                        </div>
                                        <button class="btn btn-primary px-3 ">Send</button>
                                        
                                    </form>
                                </div>

                            </div>

                        </div>
                        
                        
                    </div>
 
                    {% endfor %}
        
                </div>
            </div> 

            {% else %} 

            <div class="card">
                <div class="card-body">
                    <h1>No Post Available</h1>
                </div>
            </div>   
            {% endif %}
                
        </div>

        
    </div>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method='post' action="{% url 'comments' %}">
      <div class="modal-body">
            <input type='hidden' name="id" id='commentid'>
            <div class="form-group">
                <textarea class="form-control" name="comment" id="textarea" cols="30" rows="2"  placeholder="Post a new message"></textarea>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary">Save changes</button>
        </form>
      </div>
    </div>
  </div>
</div> 


<script>
    $(document).ready(function(){
        $("#fileInput").on("change", function(e){
            let fileList = e.target.files;
            $(fileList).each(function(i){
                let imgList = `<li>${fileList[i].name}</li>`;
                $("#imageNames").append(imgList);
            });
        }); 
        
        $(".media-reply__link button").on("click", function(){
            $('#commentid').val($(this).attr("data-id"))
        });
    });
</script>



{% endblock content %}